### ISSUE TITLE
Thelia 2.2.0 requirement seems too high

### ISSUE THREAD

**Issue by lunika** [thelia-modules/BackOfficePath#10]
Why this module requires thelia 2.2.0 ? Which feature in Thelia 2.2.0 is used ?

Thelia 2.2.0 is not stable and doing this lot of website can't use this module.

I really think it's a bad idea to do this.

**Comment by bilhackmac** [comment]
v0.3.3 is stable enough to be used with Thelia v2.0 to v2.1.5.

This big refactor use middleware

**Comment by lunika** [comment]
Middleware was introduced in version 2.1 of Thelia.

**Comment by bilhackmac** [comment]
So you can drop version requirement

**Comment by lunika** [comment]
The only feature that require Thelia 2.2.0 in this module is the ability to add multiple authors in the module.xml file...

**Comment by bilhackmac** [comment]
Changes are made in 2abebf4
