### ISSUE TITLE
Not working with some modules

### ISSUE THREAD

**Issue by enurit** [thelia-modules/BackOfficePath#8]
it doesn't work with modules which are using this->redirectToRoute method when validating form.

e.g CmCIC or Paypal modules

**Comment by zzuutt** [comment]
doesn't work with Thelia 2.2.2
when the currency is changed
`Fatal error: Call to undefined method BackOfficePath\Stack\BackOfficePathMiddleware::getContainer() in /home/zzuutt/www/dev/core/lib/Thelia/Core/Stack/ParamInitMiddleware.php on line 113`

**Comment by roadster31** [comment]
`redirectToRoute ` is depecated since 2.1.0-alpha1, and has been removed in 2.2 (I guess)
